apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openmeter-pod-runtime-watcher.fullname" . }}
  labels:
    {{- include "openmeter-pod-runtime-watcher.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openmeter-pod-runtime-watcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openmeter-pod-runtime-watcher.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openmeter-pod-runtime-watcher.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OPENMETER_URL
              value: {{ .Values.settings.openmeter_url }}
            {{- with .Values.settings.openmeter_token }}
            - name: OPENMETER_TOKEN
              value: {{ . }}
            {{- end }}
            {{- with .Values.settings.openmeter_token_secret }}
            - name: OPENMETER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: token
            {{- end }}
            - name: NAMESPACE
              value: {{ .Values.settings.namespace_override | default .Release.Namespace }}
            - name: LABEL_SELECTOR
              value: {{ .Values.settings.label_selector }}
            - name: SOURCE
              value: {{ .Values.settings.source }}
            - name: MONITOR_RATE_SECONDS
              value: {{ .Values.settings.monitor_rate_seconds | quote }}
{{/* TODO: enable health checks when we add it to the application */}}
{{/*          ports:*/}}
{{/*            - name: http*/}}
{{/*              containerPort: {{ .Values.service.port }}*/}}
{{/*              protocol: TCP*/}}
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
