apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "openmeter-pod-runtime-watcher.serviceAccountName" . }}
  labels:
    {{- include "openmeter-pod-runtime-watcher.labels" . | nindent 4 }}
  namespace: {{ .Values.settings.namespace_override | default .Release.Namespace }}
rules:
  - verbs:
      - list
    apiGroups:
      - ""
    resources:
      - pods
