apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "openmeter-pod-runtime-watcher.serviceAccountName" . }}
  labels:
    {{- include "openmeter-pod-runtime-watcher.labels" . | nindent 4 }}
  namespace: {{ .Values.settings.namespace_override | default .Release.Namespace }}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "openmeter-pod-runtime-watcher.serviceAccountName" . }}

subjects:
  - kind: ServiceAccount
    name: {{ include "openmeter-pod-runtime-watcher.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
